version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

volumes:
  postgresql_data:
    driver: local
